title: Page
pages: false
files: true
fields:
  title:
    label: Title
    type:  text
  text:
    label: Text
    type:  textarea
files:
  fields:
    caption:
      label: Bildunterschrift
      type: textarea
