title: Default
pages: false
files: true
fields:
  title:
    label: Title
    type:  text
  ismenuitem:
    label: Sichtbar im Menü
    type:  checkbox
  text:
    label: Text
    type:  textarea
files:
  fields:
    caption:
      label: Bildunterschrift
      type: textarea
